#!/usr/bin/bash

# left="false"

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

### CHECK IF ROOT
if [[ $EUID -eq 0 ]]; then # Running script as root

time='\[\033[01;31m\]$(date +%H:%M)'
pwd='\[\033[00;31m\]\w'
prompt='\[\033[00;31m\]\$'

else

time='\[\033[01;95m\]$(date +%H:%M)'
pwd='\[\033[00;34m\]\w'
prompt='\[\033[00;34m\]\$'

fi

if [ $? == 0 ]; then
	status=""
else
	status='\[\033[00;00m\] ── \[\033[01;31m\]$?\n'
fi
# ㉿
prompt="\[\033[00;00m\]╭─ \
\[\033[01;31m\]\u\
\[\033[00;00m\]@\
\[\033[01;0m\]\H\
\[\033[00;00m\] ── \
$time\
$status\
\n\
\[\033[00;00m\]├ \
$pwd\
\n\
\[\033[00;00m\]╰─\
$prompt\
\[\033[00;00m\] "

# if [ "$color_prompt" != yes ]; then
# 	prompt=$(echo -e "\[\033[00;00m\]$prompt")
# 	# prompt=${$(echo -e "$prompt")//\\/}
# 	# prompt=${$(echo -e "\[\033[00;00m\]$prompt")//[/}
# 	# prompt=${$(echo -e "$prompt")//]/}
# fi

echo "$prompt"